# Generated by Django 5.2.1 on 2025-06-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_criterio_preguntaevaluacion_puesto_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionventa',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
    ]
