# Generated by Django 5.2.1 on 2025-06-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_preguntaevaluacion_rol_evaluacionventa_incidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente')], max_length=20, null=True),
        ),
    ]
