# Generated by Django 5.2.1 on 2025-06-04 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evaluacionventa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciontrabajador',
            name='fecha_activacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
