# Generated by Django 5.2.1 on 2025-06-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_rol_admin_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('rango_min', models.IntegerField()),
                ('rango_max', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=50)),
                ('max_puntaje', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='respuestaevaluacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='respuestaevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.evaluacion'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='criterio_obtenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.criterio'),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.indicador'),
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='puntuacion',
        ),
    ]
