# Generated by Django 5.2.1 on 2025-06-03 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_criterio_indicador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEvaluacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=0)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.evaluacionventa')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicador')),
            ],
        ),
    ]
