# Generated by Django 5.1.3 on 2025-06-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_autoevaluaciontrabajador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaautoevaluaciontrabajador',
            name='puntaje',
            field=models.IntegerField(default=20),
        ),
    ]
