# Generated by Django 5.2.1 on 2025-06-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_respuestaevaluacionventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='criterio',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='indicador',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.criterio'),
        ),
        migrations.AlterField(
            model_name='criterio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
