# Generated by Django 5.2.1 on 2025-06-03 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_criterio_categoria_criterio_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='indicador',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.criterio'),
        ),
    ]
