# Generated by Django 5.1.3 on 2025-06-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_respuestaautoevaluaciontrabajador_puntaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_malo', models.PositiveSmallIntegerField(default=0)),
                ('puntaje_regular', models.PositiveSmallIntegerField(default=10)),
                ('puntaje_excellent', models.PositiveSmallIntegerField(default=20)),
                ('indicador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='core.indicador')),
            ],
        ),
    ]
