# Generated by Django 5.2.1 on 2025-06-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_indicador_categoria_alter_indicador_criterio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaevaluacionventa',
            name='evaluacion',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacionventa',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacionventa',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='respuestaevaluacionventa',
            name='evaluacion_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.evaluacionventa'),
        ),
        migrations.AddField(
            model_name='respuestaevaluacionventa',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestaevaluacionventa',
            name='puntaje_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='criterio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.criterio'),
        ),
    ]
