# Generated by Django 5.1.3 on 2025-06-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_puntajeindicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntajeindicador',
            name='puntaje_excellent',
        ),
        migrations.RemoveField(
            model_name='puntajeindicador',
            name='puntaje_malo',
        ),
        migrations.RemoveField(
            model_name='puntajeindicador',
            name='puntaje_regular',
        ),
        migrations.AddField(
            model_name='puntajeindicador',
            name='bueno',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='puntajeindicador',
            name='malo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='puntajeindicador',
            name='regular',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='puntajeindicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='core.indicador'),
        ),
    ]
