# Generated by Django 5.1.3 on 2025-06-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_puntajeindicador_puntaje_excellent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoevaluaciontrabajador',
            name='evaluador',
        ),
        migrations.AlterField(
            model_name='autoevaluaciontrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoevaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respuestaautoevaluaciontrabajador',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
