# Generated by Django 5.2.1 on 2025-06-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_indicador_criterio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='criterio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.criterio'),
        ),
    ]
