# Generated by Django 5.1.3 on 2025-06-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_autoevaluaciontrabajador_evaluador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaautoevaluaciontrabajador',
            name='valoracion',
            field=models.CharField(choices=[('Malo', 'Malo'), ('Regular', 'Regular'), ('Bueno', 'Bueno')], default='Regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='respuestaautoevaluaciontrabajador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.indicador'),
        ),
        migrations.AlterField(
            model_name='respuestaautoevaluaciontrabajador',
            name='puntaje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
