# Generated by Django 5.2.1 on 2025-06-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_indicador_criterio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaevaluacionventa',
            name='evaluacion_venta',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacionventa',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacionventa',
            name='puntaje_total',
        ),
        migrations.AddField(
            model_name='respuestaevaluacionventa',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.evaluacionventa'),
        ),
        migrations.AddField(
            model_name='respuestaevaluacionventa',
            name='indicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.indicador'),
        ),
        migrations.AddField(
            model_name='respuestaevaluacionventa',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
