# Generated by Django 5.1.3 on 2025-06-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_respuestaautoevaluaciontrabajador_valoracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaautoevaluaciontrabajador',
            name='valoracion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], default=3),
        ),
    ]
