# Generated by Django 5.2.2 on 2025-06-08 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_respuestaautoevaluaciontrabajador_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateField(auto_now_add=True)),
                ('puntaje_total', models.FloatField(default=0.0)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_totales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_evaluacion', to='core.puesto')),
            ],
            options={
                'unique_together': {('puesto', 'fecha_inicio', 'fecha_fin')},
            },
        ),
        migrations.CreateModel(
            name='PesoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTO', 'Autoevaluación'), ('TRAB', 'Evaluación Trabajador'), ('CLIE', 'Evaluación Cliente')], max_length=4)),
                ('peso', models.FloatField(help_text='Decimal entre 0 y 1, e.g. 0.5')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_evaluacion', to='core.puesto')),
            ],
            options={
                'verbose_name': 'Peso de Evaluación',
                'unique_together': {('puesto', 'tipo')},
            },
        ),
    ]
