# Generated by Django 5.2.1 on 2025-06-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usuario_rol_trabajador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionventa',
            name='trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.trabajador'),
        ),
    ]
