# Generated by Django 5.2.1 on 2025-06-03 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_evaluacionventa_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionventa',
            name='trabajador',
            field=models.ForeignKey(limit_choices_to={'rol': 'trabajador'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
