# Generated by Django 5.2.1 on 2025-06-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cliente_user_alter_evaluacionventa_trabajador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluador', models.CharField(max_length=100)),
                ('evaluado', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AUTO', 'Autoevaluación'), ('TRAB', 'Evaluación Trabajador'), ('CLIE', 'Evaluación Cliente')], max_length=4)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='PreguntaEvaluacion',
        ),
        migrations.RemoveField(
            model_name='puntajeindicador',
            name='indicador',
        ),
        migrations.AlterModelOptions(
            name='pesoevaluacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resultadototal',
            options={},
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.criterio'),
        ),
        migrations.AlterField(
            model_name='pesoevaluacion',
            name='peso',
            field=models.FloatField(help_text='Decimal entre 0 y 1 (e.g. 0.4)'),
        ),
        migrations.AlterField(
            model_name='respuestaautoevaluaciontrabajador',
            name='valoracion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AlterField(
            model_name='respuestaevaluacionventa',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.evaluacionventa'),
        ),
        migrations.AlterField(
            model_name='respuestaevaluacionventa',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicador'),
        ),
        migrations.DeleteModel(
            name='Incidencia',
        ),
        migrations.DeleteModel(
            name='PuntajeIndicador',
        ),
    ]
