# Generated by Django 5.2.3 on 2025-06-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_evaluacion_remove_incidencia_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='initial_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
