# Generated by Django 5.2.3 on 2025-06-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_trabajador_initial_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='initial_password',
        ),
        migrations.AddField(
            model_name='criterio',
            name='puestos',
            field=models.ManyToManyField(to='core.puesto'),
        ),
    ]
