# Generated by Django 5.2.3 on 2025-06-14 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_criterio_puesto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol_admin',
        ),
        migrations.AlterField(
            model_name='resultadototal',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trabajador'),
        ),
    ]
