# Generated by Django 5.2.3 on 2025-06-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_criterio_estado_criterio_peso_alter_criterio_puestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaautoevaluaciontrabajador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicador'),
        ),
    ]
