# Generated by Django 5.1.3 on 2025-06-16 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_respuestaautoevaluaciontrabajador_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluaciontrabajador',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
