# Generated by Django 5.2.3 on 2025-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_autoevaluaciontrabajador_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoevaluacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Vencido', 'Vencido')], default='Pendiente', max_length=10),
        ),
    ]
